<?php

/**
 * @file
 * Database driver for MySQLi.
 *
 * The MySQLi module provides the connection between Drupal and a MySQL, MariaDB
 * or equivalent database using the mysqli PHP extension.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mysqli_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.mysqli':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The MySQLi module provides the connection between Drupal and a MySQL, MariaDB or equivalent database using the mysqli PHP extension. For more information, see the <a href=":mysqli">online documentation for the MySQLi module</a>.', [':mysqli' => 'https://www.drupal.org/documentation/modules/mysqli']) . '</p>';
      return $output;

  }
}
